# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [15]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [16]:
# your code here
print(np.__version__)

1.26.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [17]:
# Method 1
a = np.random.random((2, 3, 5))

In [19]:
# Method 2
a = np.random.rand(2, 3, 5)

In [20]:
# Method 3
a = np.random.randint(0, 10, size=(2, 3, 5))

#### 4. Print *a*.


In [21]:
# your code here
print(a)

[[[8 6 7 7 6]
  [3 1 0 9 7]
  [3 1 2 8 4]]

 [[7 4 7 8 7]
  [5 8 0 6 5]
  [5 4 6 3 9]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [22]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [23]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [24]:
# your code here
print(a.size == b.size)  # This will print True or False


True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [25]:
# your answer here
a.shape = (2, 3, 5)
print(a.shape)

b.shape = (5, 2, 3)

print(b.shape)  # No, we cannot directly add a and b using a + b because their shapes are different.

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [26]:
# your code here
c = np.transpose(b, (1, 2, 0))
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [27]:
# your code/answer here
d = a + c # Because both arrays a and c have the same shape: (2, 3, 5)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [28]:
# your code/answer here
print("Array a:")
print(a)

print("\nArray d (a + c):")
print(d) # d is exactly the same as a

Array a:
[[[8 6 7 7 6]
  [3 1 0 9 7]
  [3 1 2 8 4]]

 [[7 4 7 8 7]
  [5 8 0 6 5]
  [5 4 6 3 9]]]

Array d (a + c):
[[[ 9.  7.  8.  8.  7.]
  [ 4.  2.  1. 10.  8.]
  [ 4.  2.  3.  9.  5.]]

 [[ 8.  5.  8.  9.  8.]
  [ 6.  9.  1.  7.  6.]
  [ 6.  5.  7.  4. 10.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [29]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [30]:
# your code/answer here
print(np.array_equal(e, a))  # This will print True

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [31]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [32]:
# your code here
f = np.empty(d.shape)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [33]:
# your code here
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [34]:
# your code here
print(d)

print(f)

[[[ 9.  7.  8.  8.  7.]
  [ 4.  2.  1. 10.  8.]
  [ 4.  2.  3.  9.  5.]]

 [[ 8.  5.  8.  9.  8.]
  [ 6.  9.  1.  7.  6.]
  [ 6.  5.  7.  4. 10.]]]
[[[ 75.  75.  75.  75.  75.]
  [ 25.  25.   0. 100.  75.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.   0.  75.  25.]
  [ 25.  25.  75.  25. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [50]:
# your code here
f_str = np.empty(d.shape, dtype=object)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f_str[i, j, k] = 'A'
            elif value == d_max:
                f_str[i, j, k] = 'E'
            elif value == d_mean:
                f_str[i, j, k] = 'C'
            elif d_min < value < d_mean:
                f_str[i, j, k] = 'B'
            elif d_mean < value < d_max:
                f_str[i, j, k] = 'D'

In [51]:
print(f_str)

[[['D' 'D' 'D' 'D' 'D']
  ['B' 'B' 'A' 'E' 'D']
  ['B' 'B' 'B' 'D' 'B']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'B']
  ['B' 'B' 'D' 'B' 'E']]]
